name: pandas-dev
channels:
  - defaults
  - conda-forge
dependencies:
  # required
  - numpy>=1.15
  - python=3
  - python-dateutil>=2.6.1
  - pytz

  # benchmarks
  - asv

  # building
  - cython>=0.28.2

  # code checks
  - black
  - cpplint
  - flake8
  - flake8-comprehensions  # used by flake8, linting of unnecessary comprehensions
  - flake8-rst>=0.6.0,<=0.7.0  # linting of code blocks in rst files
  - isort  # check that imports are in the right order
  - mypy
  - pycodestyle  # used by flake8

  # documentation
  - gitpython  # obtain contributors from git for whatsnew
  # some styling is broken with sphinx >= 2 (https://github.com/pandas-dev/pandas/issues/26058)
  - sphinx=1.8.5
  - numpydoc>=0.9.0

  # documentation (jupyter notebooks)
  - nbconvert>=5.4.1
  - nbsphinx
  - pandoc

  # testing
  - boto3
  - botocore>=1.11
  - hypothesis>=3.82
  - moto  # mock S3
  - pytest>=4.0.2
  - pytest-cov
  - pytest-mock
  - pytest-xdist
  - seaborn
  - statsmodels

  # unused (required indirectly may be?)
  - ipywidgets
  - nbformat
  - notebook>=5.7.5
  - pip

  # optional
  - blosc
  - bottleneck>=1.2.1
  - ipykernel
  - ipython>=5.6.0
  - jinja2  # pandas.Styler
  - matplotlib>=2.2.2  # pandas.plotting, Series.plot, DataFrame.plot
  - numexpr>=2.6.8
  - scipy>=1.1

  # optional for io
  - beautifulsoup4>=4.6.0  # pandas.read_html
  - fastparquet>=0.2.1  # pandas.read_parquet, DataFrame.to_parquet
  - html5lib  # pandas.read_html
  - lxml  # pandas.read_html
  - openpyxl  # pandas.read_excel, DataFrame.to_excel, pandas.ExcelWriter, pandas.ExcelFile
  - pyarrow>=0.9.0  # pandas.read_paquet, DataFrame.to_parquet, pandas.read_feather, DataFrame.to_feather
  - pyqt>=5.9.2  # pandas.read_clipboard
  - pytables>=3.4.2  # pandas.read_hdf, DataFrame.to_hdf
  - python-snappy  # required by pyarrow
  - s3fs  # pandas.read_csv... when using 's3://...' path
  - sqlalchemy  # pandas.read_sql, DataFrame.to_sql
  - xarray  # DataFrame.to_xarray
  - xlrd  # pandas.read_excel, DataFrame.to_excel, pandas.ExcelWriter, pandas.ExcelFile
  - xlsxwriter  # pandas.read_excel, DataFrame.to_excel, pandas.ExcelWriter, pandas.ExcelFile
  - xlwt  # pandas.read_excel, DataFrame.to_excel, pandas.ExcelWriter, pandas.ExcelFile
  - pyreadstat  # pandas.read_spss
